### ISSUE TITLE
[Help Wanted]: Problem with running tests when multiple schemas are present in Apicurio Registry

### ISSUE THREAD

**Issue by hpasaricekCROZ** [sngular/kloadgen#374] opened 2023-04-21 13:21 UTC
### What happened?

Hello everyone,

I am currently facing an issue while trying to create a test plan that is linked to Apicurio schema registry. I am using Docker to run my own Apicurio schema registry and Kafka.

First, I have uploaded one schema (named "FirstSchema") to Apicurio registry. Initially, I was able to successfully connect to Apicurio using the Schema Registry Config Element in my test plan. The pop-up showed that one subject was retrieved. I used the KLG-Value Schema Serializer Config to load the schema and ran tests without any issues.

However, the problem arose when I attempted to upload a second schema (or more than one schema) to the registry. After adding another schema, it was successfully loaded in the Schema Registry Config Element, and I could use it in the KLG-Value Schema Serializer. However, I encountered two exceptions when attempting to run tests. If I tried to use the first schema, I received a Null Pointer Exception on one line of code, and if I tried to use the second schema, I received a Null Pointer Exception on another line of code.

I found that I could only run the test successfully when I deleted schemas from the registry and left **only one**. I have attached a ZIP file containing the schemas and test plan for reference.

I don't know if I'm doing something wrong here so any help is appreciated.

Thanks!

[KLoadGenIssue.zip](https://github.com/sngular/kloadgen/files/11296003/KLoadGenIssue.zip)

### KloadGen Version

KloadGen 5.6.0.

### Relevant log output

```shell
FirstSchema error:
java.lang.NullPointerException: null
	at com.sngular.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.findSchema(AvroObjectCreatorFactory.java:220) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.processor.objectcreatorfactory.impl.AvroObjectCreatorFactory.isOptionalFieldAccordingToSchema(AvroObjectCreatorFactory.java:167) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.processor.SchemaProcessor.shouldProcessAccordingToSubField(SchemaProcessor.java:190) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.processor.SchemaProcessor.shouldProcessField(SchemaProcessor.java:180) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.processor.SchemaProcessor.lambda$calculateFieldsToProcess$0(SchemaProcessor.java:169) ~[kloadgen-5.6.0.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:849) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.sngular.kloadgen.processor.SchemaProcessor.calculateFieldsToProcess(SchemaProcessor.java:170) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.processor.SchemaProcessor.next(SchemaProcessor.java:42) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.loadgen.impl.AvroSRLoadGenerator.nextMessage(AvroSRLoadGenerator.java:55) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:137) ~[kloadgen-5.6.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

SecondSchema error:
java.lang.NullPointerException: null
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:?]
	at com.sngular.kloadgen.sampler.schemaregistry.impl.ApicurioSchemaRegistry.getLastestSearchedArtifact(ApicurioSchemaRegistry.java:164) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.sampler.schemaregistry.impl.ApicurioSchemaRegistry.getLatestSchemaMetadata(ApicurioSchemaRegistry.java:86) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.loadgen.impl.SRLoadGenerator.retrieveSchema(SRLoadGenerator.java:23) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.loadgen.impl.AvroSRLoadGenerator.setUpGenerator(AvroSRLoadGenerator.java:38) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:380) ~[kloadgen-5.6.0.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:74) ~[kloadgen-5.6.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dhergonsngular** [comment] 2023-04-24 06:16
Hi @hpasaricekCROZ, 

Thank you for collaborating, We will replicate the problem and get back to you as soon as possible.

Best regards

**Comment by dhergonsngular** [comment] 2023-04-28 10:24
Hello @hpasaricekCROZ, 

I have created a branch with the corrections linked to the issue. Could you test if it has the behavior you expect?

**Comment by hpasaricekCROZ** [comment] 2023-05-08 08:23
Hello @dhergonsngular.

I tested the corrections and it works now :)

The only minor bug I noticed is that now when browsing all schemas in KLG - Value Schema Serializer Config, the field Value Subject Name displays the ID of the schema instead of the Name (which was the case in the old version).

Old version:
![Snimka zaslona 2023-05-08 095633](https://user-images.githubusercontent.com/131460727/236774049-a70dd2a6-f63c-4b16-808e-cca93ad21815.png)

New version:
![Snimka zaslona 2023-05-08 095829](https://user-images.githubusercontent.com/131460727/236774080-8cf57515-3783-4ac1-b7b1-1a2bd31de0ba.png)

**Comment by dhergonsngular** [comment] 2023-05-09 06:29
Hi @hpasaricekCROZ

Exactly, unlike Confluent where we took the SubjectName for the schema search, in Apicurio we cannot take the Name as 
 a reference since it is not unique and we are limited by JMeter in this aspect.
Apicurio documentation shows how to add an ID when creating the artifact. They recommend using this functionality instead of auto-generating.
https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm#tag/Artifacts/operation/createArtifact

We will add this to the KLoadGen documentation

**Comment by hpasaricekCROZ** [comment] 2023-05-17 09:38
Hello, 

This works now as expected. Do I close the issue or will you?

**Comment by AdrianLagarteraSngular** [comment] 2023-05-17 09:46
Good to know it works with the changes now.

And don't worry about closing the issue, it will be closed when the branch that solves the problem is merged into the main branch.

Thanks again.

**Closed** 2023-05-19 10:43 UTC
