### ISSUE TITLE
[Issue] ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other

### ISSUE THREAD

**Issue by venkataklagisetty** [sngular/kloadgen#311] opened 2022-11-15 22:00 UTC
### What happened?

Hi

I am getting error from "ProtobufLoadGenerator", it is unable to load or create "Address" type or values into jmeter.
Here is the edited snippet of contract:

message Order {

  int32 order_id = 1;
  .demo.Order.CustomerAccount customer_account = 3;

  message Address {
    string address_line_one = 2;
  }
  
  message CustomerAccount {
    .demo.Order.CustomerAccount.BillingParty billing_party = 1;

    message BillingParty {
      string party_id = 3;
      .demo.Order.Address party_address = 4;
    }
  }
}

I have "Address" in "Order" but there is no variable for that.
"Address" is being using in another Message.

Jmeter is unable to load structure properly for this scenario
![image](https://user-images.githubusercontent.com/76566580/207372638-c04fb974-e9bd-4ab9-82af-0ab2fe4cfa97.png)

### KloadGen Version

KLoadGen 4.12.2

### Relevant log output

```shell
2022-11-15 15:35:45,500 ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
com.google.protobuf.Descriptors$DescriptorValidationException: demo.Order.CustomerAccount.BillingParty.party_address: ".demo.Order.Address" is not defined.
	at com.google.protobuf.Descriptors$DescriptorPool.lookupSymbol(Descriptors.java:2465) ~[kloadgen-4.12.2.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.crossLink(Descriptors.java:1480) ~[kloadgen-4.12.2.jar:?]
	at com.google.protobuf.Descriptors$FieldDescriptor.access$1000(Descriptors.java:991) ~[kloadgen-4.12.2.jar:?]
	at com.google.protobuf.Descriptors$Descriptor.crossLink(Descriptors.java:954) ~[kloadgen-4.12.2.jar:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [x] I have added the Schema

**Comment by venkataklagisetty** [comment] 2022-11-15 22:23
I think you can understand the problem by looking at error message and protobuf schema snippet

**Comment by mseijasm** [comment] 2022-11-21 08:42
Hi @venkataklagisetty,

Thank you for your collaboration. We are looking at it and we will get back to you as soon as possible.

**Comment by mseijasm** [comment] 2022-11-21 09:37
Please attach the test plan and the complete protobuf schema

**Comment by venkataklagisetty** [comment] 2022-11-21 12:21
I am vacation now, I ll connect with you after thanks giving week.

Pls don't close issue

Thank u
Venkata

**Comment by vishaldhanani** [comment] 2022-11-21 18:04
Hi @mseijasm, I'm working with @venkataklagisetty on this issue. I can provide you the schema that we are using for this issue.  Basically, we want to refer Address message on other messages (For reusability purposes) so we only put it below the Order and give references to all other places. While we are doing this at the time confluent schema registry accepts and validates schema correctly but when we load the same schema into JMeter using KLoadgen at that time KLoadgen throws the below error. 

Error: 
```
2022-11-21 11:56:54,425 ERROR n.c.k.l.i.ProtobufLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
com.google.protobuf.Descriptors$DescriptorValidationException: jbhunt.Order.CustomerAccount.BillingParty.address: ".jbhunt.Order.Address" is not defined.

```

Protobuf Schema: 
```
syntax = "proto3";
package jbhunt;

option java_package = "com.jbhunt.unmanaged.order.proto";
option java_outer_classname = "IntraOrder";
option java_multiple_files = true;

message Order {
  int32 order_id = 1;
  string order_number = 2;
  .jbhunt.Order.CustomerAccount customer_account = 3;

  message CustomerAccount {
    .jbhunt.Order.CustomerAccount.BillingParty billing_party = 1;
  
    message BillingParty {
      string party_id = 1;
      .jbhunt.Order.Address address = 2;
    }
  }
  message Address {
    string address_line_one = 1;
    string address_line_two = 2;
  }
}

```

Looking forward to getting some solution on this issue. 

Thank you,
Vishal

**Comment by mseijasm** [comment] 2022-11-29 12:54
Hi @vishaldhanani and @venkataklagisetty 

We continue working on this issue and we have maked a new commit on this issue branch.

For the moment you can now pass the values for the field type Address object. 

We have also a partial solution for the error and it is that you can refer to Address message on other messages directly with the type name, without passing the package and the parent ".jbhunt.Order".

For example, for your schema the BillingParty should be
`message BillingParty {
  string party_id = 1;
  Address address = 2;
}`
and of course, you have to keep Address message below the Order message.

We know that this isn't the standard for nested types in protobuf but we espect that you can keep working until we fix this issue definitely

**Comment by vishaldhanani** [comment] 2022-11-29 18:04
Hi @mseijasm, Thanks for sharing all the inputs on this issue. We tried declaring directly `Address` inside the BillingParty but we have `Address` as a reusable schema and we are referring to other multiple messages so we don't want to declare nested as well. Our schema is designed to use a full path for referring messages. such as  `.jbhunt.Order.Address`

**Comment by mseijasm** [comment] 2022-11-30 10:34
Hi @vishaldhanani and @venkataklagisetty 

Now I think the issue is resolved. Please check in the issue branch if it works for you and let us know.

Thanks for your collaboration.

**Comment by venkataklagisetty** [comment] 2022-11-30 17:56
Hi @mseijasm , did you release any updated version with fix?

**Comment by mseijasm** [comment] 2022-12-01 07:41
Hi @venkataklagisetty,

No, I will release an updated version with the fix as soon as posible, but you can test it already from the branch issue

**Comment by venkataklagisetty** [comment] 2022-12-01 17:36
@mseijasm , We just tried using the branch code, but we got build failure
"Cannot resolve com.github.everit-org.json-schema:org.everit.json.schema:1.14.0 "
When  I checked in maven repository, it doesnot exist
<dependency>
      <groupId>com.github.everit-org.json-schema</groupId>
      <artifactId>org.everit.json.schema</artifactId>
      <version>1.14.0</version>
    </dependency>

If possible please share us the Jar

**Comment by mseijasm** [comment] 2022-12-05 08:21
Hi @venkataklagisetty,

KLoadGen is deployed in maven central but the dependency com.github.everit-org.json-schema:org.everit.json.schema:1.14.0 has been changed to Jitpack. Please try to download it from there
https://jitpack.io/p/everit-org/json-schema

We will upload a fix to the pom file.

**Comment by venkataklagisetty** [comment] 2022-12-07 21:10
@mseijasm , please share working jar of the branch

**Comment by mseijasm** [comment] 2022-12-09 08:08
Hi @venkataklagisetty and @vishaldhanani ,

What problem do you have building the project? 
Did it work adding the _org.everit.json.schema_ dependency from Jitpack?

**Comment by mseijasm** [comment] 2022-12-09 15:49
Hi @venkataklagisetty and @vishaldhanani,

I have made a new commit.
Please try again to build the projects and tell me the errors that you encounter.

Thanks.

**Comment by venkataklagisetty** [comment] 2022-12-09 19:39
@mseijasm , We are able to create jar from branch and it resolved us "Address" issue, but we got issue with another field.
Please find below our evolved schema(by adding new array element) and error

```
syntax = "proto3";
package jbhunt;

option java_package = "com.jbhunt.unmanaged.order.proto";
option java_outer_classname = "IntraOrder";
option java_multiple_files = true;

message Order {
  int32 order_id = 1;
  string order_number = 2;
  .jbhunt.Order.CustomerAccount customer_account = 3;

  message CustomerAccount {
    .jbhunt.Order.CustomerAccount.BillingParty billing_party = 1;
  
    message BillingParty {
      string party_id = 1;
      .jbhunt.Order.Address address = 2;
      repeated .jbhunt.Order.Contact party_contact = 3;
    }
  }
  message Address {
    string address_line_one = 1;
    string address_line_two = 2;
  }
  message Contact {
    int32 contact_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string email_address = 5;
    string phone_number = 6;
  }
}
```
![image](https://user-images.githubusercontent.com/76566580/206783404-e03915dc-8b49-4d65-a594-c24fea919edf.png)

Please help us with this issue

**Comment by mseijasm** [comment] 2022-12-12 11:24
Hi @venkataklagisetty and @vishaldhanani,

I have comitted a fix for the repeated field. 
Please try and tell me if it works ok.

**Comment by venkataklagisetty** [comment] 2022-12-12 18:14
Hi @mseijasm 
Latest code resolved "repeated" error , but we evolved our schema and getting "Address" error again at different nested level.
Please take a look and resolve it to work at all nested levels.
Also please take care same issue for **"repeated"** elements

Please find below Evolved (updated) proto and Error screenshot
```
syntax = "proto3";
package demo;

option java_package = "com.demo.order.proto";
option java_outer_classname = "DemoOrder";
option java_multiple_files = true;

message Order {
  int32 order_id = 1;
  string order_number = 2;
  .demo.Order.CustomerAccount customer_account = 3;
  .demo.Order.Details details = 4;

  message CustomerAccount {
    .demo.Order.CustomerAccount.BillingParty billing_party = 1;
  
    message BillingParty {
      string party_id = 1;
      .demo.Order.Address address = 2;
      repeated .demo.Order.Contact party_contact = 3;
    }
  }
  message Address {
    string address_line_one = 1;
    string address_line_two = 2;
  }
  message Contact {
    int32 contact_id = 1;
    string contact_name = 2;
  }
  message Details {
    .demo.Order.Details.InDetails in_details = 1;
  
    message InDetails {
      .demo.Order.Details.InDetails.CustomsDetails customs_details = 1;
    
      message CustomsDetails {
        .demo.Order.Details.InDetails.CustomsDetails.Party party = 1;

        message Party {
          .demo.Order.Address party_address = 1;
          repeated .demo.Order.Contact party_contact = 2;
        }
      }      
    }
  }
}
```
![image](https://user-images.githubusercontent.com/76566580/207122224-cb32c448-908e-484c-a599-ad1a098462cf.png)

**Comment by mseijasm** [comment] 2022-12-15 16:08
Hi @venkataklagisetty and @vishaldhanani,

I have made a new commit that fix the last error with the evolved schema.
Please try it and tell me if it works ok.

Thanks.

**Comment by venkataklagisetty** [comment] 2022-12-15 17:23
@mseijasm 
Latest code fixed the problem but it failed for another field when evolved the schema.
I just added one "repeated" element to schema ,then it failed.
Please find below latest schema and error
```
syntax = "proto3";
package demo;

option java_package = "com.demo.order.proto";
option java_outer_classname = "DemoOrder";
option java_multiple_files = true;

message Order {
  int32 order_id = 1;
  string order_number = 2;
  .demo.Order.CustomerAccount customer_account = 3;
  .demo.Order.Details details = 4;

  message CustomerAccount {
    .demo.Order.CustomerAccount.BillingParty billing_party = 1;
  
    message BillingParty {
      string party_id = 1;
      .demo.Order.Address address = 2;
      repeated .demo.Order.Contact party_contact = 3;
    }
  }
  message Address {
    string address_line_one = 1;
    string address_line_two = 2;
  }
  message Contact {
    int32 contact_id = 1;
    string contact_name = 2;
  }
  message Details {
    .demo.Order.Details.InDetails in_details = 1;
  
    message InDetails {
      .demo.Order.Details.InDetails.CustomsDetails customs_details = 1;
    
      message CustomsDetails {
        .demo.Order.Details.InDetails.CustomsDetails.Party party = 1;
      
        message Party {
          .demo.Order.Address party_address = 1;
          repeated .demo.Order.Contact party_contact = 2;
          repeated .demo.Order.Contact p_contact = 3;
        }
      }
    }
  }
}
```
com.google.protobuf.Descriptors$DescriptorValidationException: demo.Order.Details.InDetails.CustomsDetails.Party.Contact.contact_id: "contact_id" is already defined in "demo.Order.Details.InDetails.CustomsDetails.Party.Contact".

![image](https://user-images.githubusercontent.com/76566580/207926326-3e16dce7-7f8f-4774-b097-5ac23449bf7b.png)

**Comment by mseijasm** [comment] 2022-12-20 14:48
Hi @venkataklagisetty and @vishaldhanani,

We have uploaded the fix to master.
Please try it and tell me if it works ok.

Thanks.

**Comment by venkataklagisetty** [comment] 2022-12-20 21:00
@mseijasm 
I just tried with master code, It fails for same error that I posted earlier 
https://github.com/corunet/kloadgen/issues/311#issuecomment-1353443337

**Comment by venkataklagisetty** [comment] 2022-12-27 16:37
Hi @mseijasm ,

With the latest jar we are not getting error but its not producing any message.
It is same schema which we shared earlier.

@vishaldhanani  got same error as well.

Please find below the log.
![image](https://user-images.githubusercontent.com/76566580/209695189-128ecb50-eceb-43cb-bb0e-2d4169b354a1.png)

**Comment by venkataklagisetty** [comment] 2022-12-27 16:59
Hi @mseijasm 
The change in package structure(net.coru to com.sngular) caused some issue for me and @vishaldhanani.
We just updated our JMX to reflect new package structure ,then it works good.

For now, the exception which we created issue got resolved.

We test and analyze it more. We will let you know if we face any issue.
Please let us know the release plan of this new jar.

**Comment by mseijasm** [comment] 2022-12-28 08:26
Hi @venkataklagisetty and @vishaldhanani 

In response to your previous comment, please add the view of the results tree to see the messages produced.

As the exception for wich you created the issue has been solved, I am going to close it. Feel free to open a new one if you find any other errors.

Thanks a lot for your collaboration.

**Closed by mseijasm** 2022-12-28 08:26 UTC
Labels: bug

**Comment by vishaldhanani** [comment] 2022-12-28 15:05
Hi @mseijasm, 
Thanks a lot for your support. Below is the result tree for successfully published messages using KLoadgen plugin with the protobuf schema. 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/29518449/209831142-9a64e6ea-cd85-47e7-8134-99ccbc3492ec.png">

Please let us know the release plan for this new jar or share the link to the latest releases.

Thank you @venkataklagisetty for troubleshooting this issue! 

Thank you,
Vishal

**Comment by mseijasm** [comment] 2022-12-29 10:22
Hi @vishaldhanani and @venkataklagisetty 

There is a new release in Maven Central, with the version 5.2.7
You cand find it here: https://repo.maven.apache.org/maven2/com/sngular/kloadgen/5.2.7/

Thanks.
